### PR TITLE
support unpickle of python builtin set

### PR DESCRIPTION
**Pull request by grooveygr**

### CODE REVIEW

**Comment by grooveygr** [comment]
Closes #19

**Comment by hydrogen18** [comment]
I just saw this MR. The changes don't look too serious. But is there any test coverage over this new behavior?

**Comment by grooveygr** [comment]
Right!
Added a sanity test in spirit of the other protocol0 tests.

**Comment by hydrogen18** [comment]
I'll do some additional review of this soon-ish and let you know.

**Comment by hydrogen18** [comment]
I am working on integrating this change and making it a bit more generic ( to handle common python types) at the same time

**Pull request merged**
